# Generated by Django 3.0.5 on 2021-02-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210214_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
