# Generated by Django 3.0.5 on 2021-02-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
