# Generated by Django 3.0.5 on 2021-02-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_post',
        ),
    ]
